# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sajjad Heydari's Blog
email: MCSHemail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! I'm Sajjad, A cs student, a programmer, secret elephent hunter
  and member of a super secret group called human species. You can find my
  blogs here, and learn more about me in the about page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mcsh.github.io" # the base hostname & protocol for your site
twitter_username: Sajjad_Heydari
github_username:  MCSH

# Build settings
markdown: kramdown
